version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - sleepr-data:/data/db

#  reservations:
#    build:
#        context: ./
#        dockerfile: ./apps/reservations/Dockerfile
#        target: development
#
#    command: npm run start:dev reservations
#    env_file:
#      - ./apps/reservations/.env
#    ports:
#      - "3000:3000"
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#
#  auth:
#    build:
#      context: ./
#      dockerfile: ./apps/auth/Dockerfile
#      target: development
#
#    command: npm run start:dev auth
#    env_file:
#      - ./apps/auth/.env
#    ports:
#      - "3001:3001"
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules


volumes:
  sleepr-data:
